sudo: required

services:
    - docker

install:
    - docker build -t qingcloud/docker-plugin-hostnic .
after_success:
    - docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
    - if [ "$TRAVIS_BRANCH" == "master" ]; then
        docker push qingcloud/docker-plugin-hostnic;
      else
        echo $TRAVIS_BRANCH;
        docker tag qingcloud/docker-plugin-hostnic qingcloud/docker-plugin-hostnic:$TRAVIS_BRANCH;
        docker push qingcloud/docker-plugin-hostnic:$TRAVIS_BRANCH;
      fi
